# Generated by Django 4.2.13 on 2025-01-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.invoice'),
        ),
    ]
