# Generated by Django 4.2.13 on 2024-10-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_clinicday'),
        ('appointment', '0017_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcategory',
            name='available_days',
            field=models.ManyToManyField(to='clinic.clinicday'),
        ),
    ]
