# Generated by Django 4.2 on 2025-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
