# Generated by Django 4.2.13 on 2024-10-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_clinicpeople_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
