# Generated by Django 4.2.13 on 2024-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_clinicday'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='enable_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='enable_sms',
            field=models.BooleanField(default=True),
        ),
    ]
