# Generated by Django 4.2.13 on 2024-10-30 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'.", regex='^[\\+\\d{10,18}]?(?:[\\d\\-.\\s()]{10,20})$')]),
        ),
    ]
